export interface CigarBrand {
  brand: string;
  vitolas: string[];
}

export const cigarBrands: CigarBrand[] = [
  {
    brand: "Bolívar",
    vitolas: [
      "Belgravia",
      "Belicoso Fino",
      "Libertador",
      "Petit Corona",
      "Royal Corona",
      "Tubos No.2",
      "Tubos No.3",
    ],
  },
  {
    brand: "Cohiba",
    vitolas: [
      "Corona Especial",
      "Esplendido",
      "Exquisito",
      "Lanceros",
      "Maduro 5 Genios",
      "Maduro 5 Magicos",
      "Maduro 5 Secretos",
      "Medio Siglo",
      "Panetela",
      "Piramides Extra",
      "Robusto",
      "Siglo I",
      "Siglo II",
      "Siglo III",
      "Siglo IV",
      "Siglo VI",
      "Talisman (special release)",
    ],
  },
  {
    brand: "Cuaba",
    vitolas: ["Distinguidos", "Divinos", "Salomones", "Tradicionales"],
  },
  {
    brand: "Diplomáticos",
    vitolas: ["No.2"],
  },
  {
    brand: "El Rey del Mundo",
    vitolas: ["Choix Supreme", "Demi Tasse"],
  },
  {
    brand: "H. Upmann",
    vitolas: [
      "Connoisseur A",
      "Connoisseur B",
      "Connoisseur No.1",
      "Corona Major",
      "Corona Minor",
      "Half Corona",
      "Magnum 46",
      "Magnum 50",
      "Magnum 54",
      "No.2",
      "Robusto",
      "Royal Robusto (special release)",
    ],
  },
  {
    brand: "Hoyo de Monterrey",
    vitolas: [
      "Churchill",
      "De San Juan",
      "Du Depute",
      "Du Maire",
      "Elegantes (special release)",
      "Epicure Especial",
      "Epicure No.1",
      "Epicure No.2",
      "Epicure de Luxe (special release)",
      "Hermoso No.4",
      "Petit Robusto",
      "Selección No.1",
      "Selección No.2",
    ],
  },
  {
    brand: "Juan Lopez",
    vitolas: [
      "Selección No.1",
      "Selección No.2",
      "Selección Superba (special release)",
    ],
  },
  {
    brand: "Montecristo",
    vitolas: [
      "Churchills",
      "Double Edmundo",
      "Edmundo",
      "Media Corona",
      "No.1",
      "No.2",
      "No.3",
      "No.4",
      "No.5",
      "Open Eagle",
      "Open Junior",
      "Open Master",
      "Open Regata",
      "Petit Edmundo",
      "Petit No.2",
    ],
  },
  {
    brand: "Partagás",
    vitolas: [
      "898",
      "Corona Gorda",
      "Culebras (special release)",
      "Lusitania",
      "Petit Corona Especiale",
      "Presidente",
      "Serie D No.4",
      "Serie D No.5",
      "Serie D No.6",
      "Serie E No.2",
      "Serie P No.2",
      "Short",
    ],
  },
  {
    brand: "Por Larrañaga",
    vitolas: ["Montecarlo", "Petit Corona", "Picadores"],
  },
  {
    brand: "Punch",
    vitolas: ["Double Corona", "Punch Punch", "Punch Punch 48 (special release)"],
  },
  {
    brand: "Quai d’Orsay",
    vitolas: ["No.50"],
  },
  {
    brand: "Rafael González",
    vitolas: ["Perla", "Petit Corona"],
  },
  {
    brand: "Ramón Allones",
    vitolas: [
      "Allones Superiores (special release)",
      "Gigantes",
      "Small Club Corona",
      "Specially Selected",
    ],
  },
  {
    brand: "Romeo y Julieta",
    vitolas: [
      "Belicoso",
      "Cedros No.2",
      "Cedros No.3",
      "Cedros de Luxe (special release)",
      "Churchill",
      "Exhibition No.4",
      "No.1",
      "No.2",
      "Petit Churchill",
      "Petit Corona",
      "Petit Royal",
      "Piramides",
      "Short Churchill",
      "Wide Churchill",
    ],
  },
  {
    brand: "San Cristóbal de La Habana",
    vitolas: ["El Principe", "La Fuerza", "La Punta"],
  },
  {
    brand: "Trinidad",
    vitolas: ["Coloniales", "Fundadores", "La Trova (special release)", "Reyes", "Vigia"],
  },
  {
    brand: "Vegas Robaina",
    vitolas: ["Clasico", "Don Alejandro", "Familiar", "Famoso", "Unico"],
  },
];
